### ISSUE TITLE
Newspaper Prefab

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#10]
#### Acceptance Criteria
- [x] *Developer should be able to click on an article to reveal text and move to the next page from there*

#### Tasks
- [x] *Create a newspaper template*

#### Prerequisites
- [x] *The other team has a mock up created*
- [x] *We have the necessary assets*

**Comment by cfines** [comment]
done'd
