### ISSUE TITLE
Change Border Colors and Re-Import Red Line/String for BEFORE Section

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#106]
#### Acceptance Criteria
- [x] *tina approves it*

#### Tasks
- [x] *adjust colors based on the hex code doc https://docs.google.com/document/d/13qjGcoNhsoLxSBMF1Ws8qu-IvKHWoHw6lgsxfC9HKCQ/edit *

#### Prerequisites
- [x] *import updated straight red line as a separate image not bound to the bottom part of the border*
