### ISSUE TITLE
Readjust Prefabs

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#11]
#### Acceptance Criteria
- [x] *Icon is actually within the screen & doesn't disappear*
- [x] *Dropdown menu scale is adjusted to appear properly when selected*

#### Tasks
- [x] *Shift the TestPrefab_v5 slightly down so that the icon is not overlapped by the Pixel's inner camera*
- [x] *Resize the dropdown menu prefab options so that they are much larger and easier to click on*
- [x] *Also remove the fade from the title screen lol*

**Comment by Prot0ast** [comment]
@cfines let it percolate, u got this

**Comment by cfines** [comment]
mostly done, need the phone again to see where to shift the icon down so its below the camera. ill do it 2morrow
