### ISSUE TITLE
Create & Adjust Border Templates for the other sections

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#12]
#### Acceptance Criteria
- [x] *Preexisting border design for before section is adjusted to suit the changes in the original prefab_v5*
- [x] *New borders are made for the during and after sections*

#### Tasks
- [x] *Create the ui border designs for during & after*
- [x] *Set each of the border designs to prefabs*
- [x] *Adjust the preexisting prefab*

#### Prerequisites
- [x] *We have the designs for the borders finalized*

**Comment by cfines** [comment]
prefab has been made for each section. LGTM!
