### ISSUE TITLE
Add a "this app has sound" screen when opening the app

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#128]
#### Acceptance Criteria
- [ ] *This app has sound*
- [ ] *This app has branching paths*

#### Tasks
- [ ] *Include the fade-in to mention that this app has sound & branching paths*

#### Prerequisites
- [x] *We have reached a consensus on the text to be included*

#### Copy & Paste text

Kizuna: Bonds Beyond Incarceration integrates sound as a part of the experience.
[Sound Icon]
Kizuna explores different stories and aspects of the following events in a branching path structure.  For the complete experience, we encourage you to go back and browse alternate choices either as you play or once you reach the ending.

**Comment by CCrawfordUOP** [comment]
My proposed text for this page.  I'm not 100% satisfied with it so feel free to edit.  Also, I'm not sure if there's a separate place the group is using for text content review, but if there is @cfines or @Prot0ast could you please share it there if it's needed?   Thanks.


This app [could be replaced with app name] integrates sound as an integral part of the experience.
[Sound Icon]

This app [could be replaced with app name] uses a branching-path narrative structure, and the content you experience will be slightly different depending on the options you choose.  For a complete experience, we encourage you to go back and browse through the different parts after you reach the ending.

**Comment by Prot0ast** [comment]
I can ping the writing team on this if you'd like
@keiwong57 @KGTrammel

**Comment by cfines** [comment]
it's added. i reworded the branching tree explanation to make it shorter, and we are able to adjust the timings and how long these text sections appear before the title screen.
