### ISSUE TITLE
Adding Audio Stops to after the 9066 transition

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#133]
#### Acceptance Criteria
- [x] *Background music should stop once the user presses continue on the people in the Pacific Weekly section*

#### Tasks
- [x] *Attach the audio volume reduction script behavior to the continue button's on click events*
- [x] *Ensure that audio is manually reset for the scenes before and after this occurrence*

#### Prerequisites
- [x] *Script for this is fully functional*

**Comment by CCrawfordUOP** [comment]
Done in #169 :)
