### ISSUE TITLE
Selectable Text (for accessibility)

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#15]
#### Acceptance Criteria
- [ ] *User is able to select text*

#### Tasks
- [ ] *Add script to text objects (probably via text tag) to allow them to be selectable*

#### Prerequisites
- [ ] *We understand how to implement this*
- [ ] *Discuss with cube chris how to get this working with android and ios specifics*

**Comment by cfines** [comment]
https://answers.unity.com/questions/962415/make-a-ui-text-box-with-selectable-text.html

**Comment by Prot0ast** [comment]
omitting from app due to inaccessibility on app version, opting for alternative solution

**Comment by CCrawfordUOP** [comment]
Found this as a possible resource, will investigate further tomorrow to see if it's feasible to implement in time.

https://github.com/mikrima/UnityAccessibilityPlugin


2nd option could be running all the text through an open source text-to-speech engine and adding a touch icon to each page that will play the pre-recorded synthesized speech files.  If we go this route, I would want to add a toggle to the options page to allow for the speech audio to auto start playing on page load.

Again, all this time permitting.
