### ISSUE TITLE
[General]

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#16]
#### Acceptance Criteria
- [ ] *all text can be resized from the options menu*

#### Tasks
- [ ] *slider in the options that modify all every tagged text object*
- [ ] *create a script with a static variable (so it carries over to different scenes) that saves the font size slider value from the options*
- [ ] *take into account the text overflow when resized to a large size (have the page scroll-able when it overflows)*

#### Prerequisites
- [ ] *every text object is tagged to the same thing*
- [ ] *we know how to handle the text overflow*
