### ISSUE TITLE
Sound in the app

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#17]
#### Acceptance Criteria
- [x] *appropriate background music and ambience based on the page the user would be on*

#### Tasks
- [x] *write a script that handles audio that seamlessly carries over between scenes (background music and ambient sounds)*
- [x] *utilize the YouTube tutorial for creating a non destructible audio source that pans through each scene*
- [x] *change the AudioClip when it reaches a different scene to the appropriate one*

#### Prerequisites
- [x] *figure out how to do it*
- [x] *actually get the sound files*

**Comment by Prot0ast** [comment]
bro I just need the title on god on foe nem grave g no printer all fax blood gang gang gang

**Comment by Prot0ast** [comment]
aside from the substitute audio I'm waiting on, we have appropriate music for each scene :)
