### ISSUE TITLE
Title Page Slideshow

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#18]
#### Acceptance Criteria
- [x] *The user should be able to see 3 pictures cycle between set time intervals*
- [x] *The transitions for each picture is not abrupt*

#### Tasks
- [x] *Create a script that cycles between each of the images*
- [x] *Include serialized fields to drop in the images that will be used onto the script*

#### Prerequisites
- [x] *We have the pictures decided*

**Comment by Prot0ast** [comment]
:)
