### ISSUE TITLE
[General] Experimental Audio System Rework

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#185]
#### Acceptance Criteria
- [x] Mute Music and Mute SFX toggles work

#### Tasks
- [x] Create separate dedicated SFXAudio Source
- [x] Route all audio sources through a main mixer
- [x] Reassign all sfx to fit new system
- [x] make script to control mixer from options page
- [x] make sure everything still works

**Comment by CCrawfordUOP** [comment]
Made decent progress, but need to stop for the night.  Pushed changes to give-it-a-name.  

@Prot0ast @cfines could you take a look at this in the morning?  I think I'll need about 30min to re-link all sfx, but I'm not sure about fixing the toggles.

Summary of changes:
Implemented Audio Mixer
- Audio now split into two separate sources, one for Music, one for SFX.
- Both audio sources are then routed to the mixer.
- Toggles on options menu control the volume of the channels on the audio mixer, which persist between scenes.

Bugs:
-Toggles always default to show on when loading options screen and do not read current value of relevant bool.
-Most sfx are broken and need to be relinked using the updated scripts.

**Comment by CCrawfordUOP** [comment]
Toggles work, so I will close this.  Will make fixing the toggle states a new request.
