### ISSUE TITLE
Add Newspaper Pages For El Joaquin

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#22]
#### Acceptance Criteria
- [x] *the newspaper pages of el joaquin have been created*

#### Tasks
- [x] *add the content of each newspaper page onto the newpaper scenes*

#### Prerequisites
- [x] *newspaper prefab is finalized*

**Comment by cfines** [comment]
done with epicness
