### ISSUE TITLE
Change All Back Buttons To Their Proper Page, And Not LastVisitedScene()

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#23]
#### Acceptance Criteria
- [x] *Every back button on click event will use the proper change scene function*
- [x] *Creating future pages, back buttons will continue to be properly assigned, and not use LastVisitedScene() unless absolutely needed*

#### Tasks
- [x] *change all on click events for every back button in the DURING section so it leads to their specified change scene function, NOT using LastVisitedScene()*

#### Prerequisites
- [x] *there is a back button*
