### ISSUE TITLE
Rohwer Outpost Newspaper Articles Section

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#24]
#### Acceptance Criteria
- [x] *Rohwer Outpost article pages are implemented*

#### Tasks
- [x] *complete the same steps as the El Joaquin setup*

#### Prerequisites
- [x] *assets in possession*
- [x] *newspaper prefab completed*

**Comment by cfines** [comment]
done yuuuh full send yuuuh
