### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#37]
#### Acceptance Criteria
- [x] *The README file is updated to include the following:*
- [x] *General Description of the App*
- [x] *How the App functions*
- [x] *Screenshots of the App*

#### Tasks
- [x] *Write a general description of the app*
- [x] *Write out how exactly the app works*
- [x] *Get at least 4 screenshots of the app*

#### Prerequisites
- [x] *The app is 100% done lol*

**Comment by Prot0ast** [comment]
Aside from including the links to download the app on the app store (which don't exist as of this message), this README should be good to go.
