### ISSUE TITLE
Section Select

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#4]
#### Acceptance Criteria
- [x] *User should be able to traverse between the before, during, and after sections in the app*
- [x] *User should be able to access this under the hamburger icon*

#### Tasks
- [x] *Use the ChangeScene script to allow for quick navigation*
- [x] *Extend the dropdown menu options to include before, during, and after*

#### Prerequisites
- [x] *We have the needed functions in ChangeScene*
- [x] *We have the dropdown prefab PACKED in each scene it is used*

**Comment by cfines** [comment]
asdfgn yeah its done
