### ISSUE TITLE
Options Page

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#41]
#### Acceptance Criteria
- [x] *User is able to enable the sfx or music separately*

#### Tasks
- [x] *Implement these sounds in the scenes where it would be present*
- [x] *The buttons in the options will correspond with music or sfx accordingly*

#### Prerequisites
- [x] *We have the audio files*

**Comment by CCrawfordUOP** [comment]
In progress, see #185.
