### ISSUE TITLE
Section Select Page

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#42]
#### Acceptance Criteria
- [x] *The Section Select page has 3 buttons that jump to specific sections in the app*

#### Tasks
- [x] *Create the Section Select scene with 3 buttons*
- [x] *These buttons will jump to specific sections of the app*

#### Prerequisites
- [x] *This stupid meeting is over so we can actually start working*

**Comment by cfines** [comment]
done
