### ISSUE TITLE
Swiping Transitions

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#43]
#### Acceptance Criteria
- [x] *Transitions between pages between pacific weekly to students of the pacific weekly*

#### Tasks
- [x] *dissolve transition to splash screens*

#### Prerequisites
- [x] *i have the time to*

**Comment by cfines** [comment]
holy heck its done
