### ISSUE TITLE
Transition into Executive Order

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#44]
#### Acceptance Criteria
- [x] *The transition to the executive order section matches Tina's mockup*

#### Tasks
- [x] *make a script specific for this transition*

#### Prerequisites
- [x] *i have the time*

**Comment by cfines** [comment]
yer
