### ISSUE TITLE
Create a "Neeb" Prefab

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#5]
#### Acceptance Criteria
- [x] *Developers should be able to click and drag a default template of the bio screen page*
- [x] *Each of the needed scripts, textboxes, and blank image templates should be included as well*

#### Tasks
- [x] *Develop a script for the prefab that incorporates the links to different sections*
*Create a game object that includes the following as its children:*
- [x] *script for navigation*
- [x] *buttons to go back and go forward*
- [x] *box-thing that can easily include whatever asset we incorporate in the end*
- [x] *an empty text box for story*
- [x] *an empty text box for the title of the section*

**Comment by Prot0ast** [comment]
realized that we finally came up with a better name for the template than the gibberish neeb and I didn't put that here, lol
