### ISSUE TITLE
Adding all the cute stuff

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#6]
#### Acceptance Criteria
- [x] *Images, audio, and such is now present in the app when the user is using it*

#### Tasks
- [x] *Copy and paste all the assets onto the placeholders present throughout the app*
- [x] *Script for audio handling*
- [x] *Audio is added in the specified sections of the app*

#### Prerequisites
- [x] *The entire skeleton of the app is completed*
- [x] *We have all the assets in our possession*
- [x]  *We know where to put the suggested audio*

**Comment by Prot0ast** [comment]
in need of lantern send off animation

**Comment by Prot0ast** [comment]
we got lantern :D
