### ISSUE TITLE
Updated During Section Borders

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#63]
#### Acceptance Criteria
- [x] *its done and used throughout all during section pages*

#### Tasks
- [x] *make prefab for new during section borders*

#### Prerequisites
- [x] *download the updated during section borders*

**Comment by cfines** [comment]
yeh, tina approved
