### ISSUE TITLE
Change Placeholder Images

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#68]
#### Acceptance Criteria
- [x] *no more placeholder images are present*

#### Tasks
- [x] *comb through all pages and change all placeholder images to their finalized images provided in the teams*

#### Prerequisites
- [x] *we have all images in possession*

**Comment by Prot0ast** [comment]
no more placeholders!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
