### ISSUE TITLE
after wwii camps

### ISSUE THREAD

**Issue by cfines** [uop-libraries/CreativeResponse2022#69]
#### Acceptance Criteria
- [ ] * its left sided*

#### Tasks
- [ ] * change it to left sded*

#### Prerequisites
- [ ] * there bis texrt*

**Comment by cfines** [comment]
it was a test
