### ISSUE TITLE
General Navigation

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#8]
#### Acceptance Criteria
- [x] *User should be able to go through the entire app and not run into a dead end*

#### Tasks
- [x] *Create placeholders of the screens using the prefab templates*
- [x] *Add links to each of the scenes to navigate to and from them*

#### Prerequisites
- [x] *Bio prefab is created*
- [x] *Drop down menu prefab is created*
- [x] *The writing team has finalized the flow of pages*

**Comment by Prot0ast** [comment]
@cfines just add the stuff for rohwer outpost and this is gtg. I have provided the change scene functions and blank scenes for u :)

**Comment by Prot0ast** [comment]
lmao
