### ISSUE TITLE
Adding Fancier Transitions

### ISSUE THREAD

**Issue by Prot0ast** [uop-libraries/CreativeResponse2022#9]
#### Acceptance Criteria
- [x] *User should be able to see smooth transitions between the scenes*

#### Tasks
- [x] *Add smooth "relevant" transitions between the scenes*

#### Prerequisites
- [x] *Tina finished designing everything*
- [x] *General navigation is completed*

**Comment by cfines** [comment]
yeh
